import { useEffect, useMemo, useState } from 'react';
import Modal from '../ui/Modal';
import Button from '@/components/ui/action-button';
import { Input, Select, Textarea } from '@/components/form/fields';
import { formatCurrency } from '../../utils/format';

// ── Salary slip HTML ──────────────────────────────────────────────────────────
function buildSalarySlipHtml({ employee, amount, month, notes, deductions, date }) {
  const fmt = (n) => 'PKR ' + Math.round(Number(n) || 0).toLocaleString('en-PK');
  const fmtDate = (d) => new Date(d).toLocaleDateString('en-PK', { day: '2-digit', month: 'long', year: 'numeric' });
  const deductionTotal = deductions.reduce((s, d) => s + Number(d.amount || 0), 0);
  const grossSalary = amount + deductionTotal;

  const deductRows = deductions.map(d => `
    <div class="row deduct">
      <span class="label">Deduction — ${d.description || 'Advance'}</span>
      <span class="value red">-${fmt(d.amount)}</span>
    </div>`).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Salary Slip — ${employee.name}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, system-ui, sans-serif; background: #f0fdf4; display: flex; justify-content: center; padding: 20px; }
  .slip { width: 380px; border-radius: 16px; overflow: hidden; box-shadow: 0 8px 30px rgba(0,0,0,.12); }
  .header { background: linear-gradient(135deg, #10b981 0%, #059669 100%); color: #fff; padding: 28px 24px 22px; text-align: center; }
  .header h1 { font-size: 22px; font-weight: 700; letter-spacing: -.3px; }
  .header .date { font-size: 12px; opacity: .8; margin-top: 4px; }
  .avatar { width: 52px; height: 52px; border-radius: 50%; background: rgba(255,255,255,.25); display: flex; align-items: center; justify-content: center; margin: 0 auto 12px; font-size: 22px; font-weight: 700; }
  .body { background: #fff; padding: 20px; }
  .row { display: flex; justify-content: space-between; align-items: center; padding: 9px 0; border-bottom: 1px solid #f3f4f6; font-size: 13px; }
  .row:last-child { border-bottom: none; }
  .label { color: #6b7280; }
  .value { font-weight: 600; color: #111; }
  .value.red { color: #e11d48; }
  .total { background: #f0fdf4; border-radius: 10px; padding: 14px 16px; margin-top: 14px; display: flex; justify-content: space-between; align-items: center; }
  .total-label { color: #065f46; font-weight: 700; font-size: 14px; }
  .total-value { color: #059669; font-size: 22px; font-weight: 800; font-variant-numeric: tabular-nums; }
  .footer { text-align: center; font-size: 11px; color: #9ca3af; padding: 12px 20px; background: #fafafa; border-top: 1px solid #f3f4f6; }
  @media print { body { background: none; padding: 0; } .slip { box-shadow: none; } }
</style>
</head>
<body>
<div class="slip">
  <div class="header">
    <div class="avatar">${(employee.name || 'E').charAt(0).toUpperCase()}</div>
    <h1>Salary Slip</h1>
    <div class="date">${fmtDate(date)}</div>
  </div>
  <div class="body">
    <div class="row"><span class="label">Employee</span><span class="value">${employee.name}</span></div>
    ${employee.role ? `<div class="row"><span class="label">Role</span><span class="value">${employee.role}</span></div>` : ''}
    ${employee.phone ? `<div class="row"><span class="label">Phone</span><span class="value">${employee.phone}</span></div>` : ''}
    ${month ? `<div class="row"><span class="label">Month</span><span class="value">${month}</span></div>` : ''}
    ${deductionTotal > 0 ? `<div class="row"><span class="label">Gross Salary</span><span class="value">${fmt(grossSalary)}</span></div>` : ''}
    ${deductRows}
    ${notes ? `<div class="row"><span class="label">Notes</span><span class="value">${notes}</span></div>` : ''}
    <div class="total">
      <span class="total-label">Net Salary Paid</span>
      <span class="total-value">${fmt(amount)}</span>
    </div>
  </div>
  <div class="footer">Generated by OsaTech POS</div>
</div>
<script>window.onload = function() { window.print(); };<\/script>
</body>
</html>`;
}

function buildWhatsAppText({ employee, amount, month, notes, deductions, date }) {
  const fmt = (n) => 'PKR ' + Math.round(Number(n) || 0).toLocaleString('en-PK');
  const fmtDate = (d) => new Date(d).toLocaleDateString('en-PK', { day: '2-digit', month: 'long', year: 'numeric' });
  const deductionTotal = deductions.reduce((s, d) => s + Number(d.amount || 0), 0);
  const grossSalary = amount + deductionTotal;

  let text = `*Salary Slip*\n`;
  text += `Employee: ${employee.name}\n`;
  if (employee.role) text += `Role: ${employee.role}\n`;
  if (month) text += `Month: ${month}\n`;
  text += `Date: ${fmtDate(date)}\n`;
  if (deductionTotal > 0) {
    text += `\nGross Salary: ${fmt(grossSalary)}\n`;
    for (const d of deductions) {
      text += `Deduction (${d.description || 'Advance'}): -${fmt(d.amount)}\n`;
    }
  }
  text += `\n*Net Salary Paid: ${fmt(amount)}*`;
  if (notes) text += `\nNotes: ${notes}`;
  return text;
}

// ── Component ─────────────────────────────────────────────────────────────────
export default function PaySalaryModal({ open, onClose, onSubmit, employee, accounts = [], advances = [] }) {
  const [amount, setAmount] = useState('');
  const [month, setMonth] = useState('');
  const [accountId, setAccountId] = useState('');
  const [notes, setNotes] = useState('');
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);

  // After payment — show slip
  const [paid, setPaid] = useState(null); // { amount, month, notes, deductions, date }

  // Pending deductions for this employee
  const pendingDeductions = useMemo(() => {
    if (!employee) return [];
    return advances.filter(
      (a) =>
        String(a.employee_id) === String(employee.id) &&
        a.deduct_from_salary == 1 &&
        !a.salary_applied
    );
  }, [advances, employee]);

  const [selectedDeductIds, setSelectedDeductIds] = useState([]);

  useEffect(() => {
    if (open) {
      setAmount(employee?.monthly_salary ?? '');
      setMonth('');
      setAccountId('');
      setNotes('');
      setError('');
      setSaving(false);
      setPaid(null);
      // pre-select all pending deductions
      setSelectedDeductIds(pendingDeductions.map((d) => d.id));
    }
  }, [open, employee]);

  // recalculate net amount when selection changes
  const selectedDeductions = pendingDeductions.filter((d) => selectedDeductIds.includes(d.id));
  const deductionTotal = selectedDeductions.reduce((s, d) => s + Number(d.amount || 0), 0);
  const grossAmount = Number(employee?.monthly_salary || 0);
  const netAmount = Math.max(0, (Number(amount) || 0));

  const toggleDeduct = (id) => {
    setSelectedDeductIds((prev) =>
      prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id]
    );
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    const amt = netAmount;
    if (!amt || amt < 0) {
      setError('Enter a valid amount');
      return;
    }
    setSaving(true);
    try {
      const now = new Date().toISOString();
      await onSubmit({ amount: amt, month, notes, accountId: accountId || null, deductions: selectedDeductions, deductionTotal });
      setPaid({ amount: amt, month, notes, deductions: selectedDeductions, date: now });
    } catch (err) {
      setError(err.response?.data?.error || 'Unable to record payment');
    } finally {
      setSaving(false);
    }
  };

  const handlePrint = () => {
    if (!paid) return;
    const html = buildSalarySlipHtml({ employee, ...paid });
    const w = window.open('', '_blank', 'width=500,height=720');
    if (w) { w.document.write(html); w.document.close(); }
  };

  const handleWhatsApp = () => {
    if (!paid) return;
    const text = buildWhatsAppText({ employee, ...paid });
    window.open('https://wa.me/?text=' + encodeURIComponent(text), '_blank');
  };

  // ── Post-payment slip view ────────────────────────────────────────────────
  if (paid) {
    return (
      <Modal open={open} onClose={onClose} title="Payment Recorded" width="max-w-sm">
        <div className="flex flex-col items-center gap-4 py-2">
          <div className="w-14 h-14 rounded-full bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center">
            <svg className="w-7 h-7 text-emerald-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
            </svg>
          </div>
          <div className="text-center">
            <p className="text-lg font-bold text-ink">{formatCurrency(paid.amount)}</p>
            <p className="text-sm text-muted-foreground">
              Salary paid to <span className="font-medium text-ink">{employee?.name}</span>
              {paid.month ? ` for ${paid.month}` : ''}
            </p>
            {paid.deductions.length > 0 && (
              <p className="text-xs text-amber-600 mt-1">
                {paid.deductions.length} deduction{paid.deductions.length > 1 ? 's' : ''} applied ({formatCurrency(paid.deductions.reduce((s, d) => s + Number(d.amount || 0), 0))})
              </p>
            )}
          </div>
          <div className="flex gap-2 w-full">
            <button
              onClick={handlePrint}
              className="flex-1 flex items-center justify-center gap-2 rounded-xl border border-border bg-card px-3 py-2.5 text-sm font-medium hover:bg-muted/60 transition-colors"
            >
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
              </svg>
              Print Slip
            </button>
            <button
              onClick={handleWhatsApp}
              className="flex-1 flex items-center justify-center gap-2 rounded-xl border border-emerald-500/30 bg-emerald-500/5 px-3 py-2.5 text-sm font-medium text-emerald-700 hover:bg-emerald-500/10 transition-colors"
            >
              <svg className="w-4 h-4" viewBox="0 0 24 24" fill="currentColor">
                <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z"/>
              </svg>
              WhatsApp
            </button>
          </div>
          <button onClick={onClose} className="text-sm text-muted-foreground hover:text-ink transition-colors">Close</button>
        </div>
      </Modal>
    );
  }

  // ── Main form ─────────────────────────────────────────────────────────────
  return (
    <Modal
      open={open}
      onClose={onClose}
      title={`Pay Salary — ${employee?.name || ''}`}
      width="max-w-md"
      footer={
        <>
          <Button variant="secondary" onClick={onClose}>Cancel</Button>
          <Button onClick={handleSubmit} disabled={saving}>
            {saving ? 'Saving…' : 'Pay Salary'}
          </Button>
        </>
      }
    >
      <form onSubmit={handleSubmit} className="flex flex-col gap-4">
        {/* Pending deductions */}
        {pendingDeductions.length > 0 && (
          <div className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-3">
            <p className="text-xs font-bold text-amber-700 uppercase tracking-wider mb-2">
              Pending Deductions ({pendingDeductions.length})
            </p>
            <div className="flex flex-col gap-2">
              {pendingDeductions.map((d) => (
                <label key={d.id} className="flex items-center gap-3 cursor-pointer select-none">
                  <input
                    type="checkbox"
                    checked={selectedDeductIds.includes(d.id)}
                    onChange={() => toggleDeduct(d.id)}
                    className="w-4 h-4 accent-amber-600"
                  />
                  <div className="flex-1 min-w-0">
                    <p className="text-xs text-ink truncate">{d.description || 'Advance'}</p>
                  </div>
                  <span className="text-xs font-bold text-amber-700 font-mono">{formatCurrency(d.amount)}</span>
                </label>
              ))}
            </div>
            {selectedDeductions.length > 0 && (
              <div className="mt-2 pt-2 border-t border-amber-500/20 flex justify-between text-xs">
                <span className="text-amber-700">Total deductions</span>
                <span className="font-bold text-amber-700">{formatCurrency(deductionTotal)}</span>
              </div>
            )}
          </div>
        )}

        <Input
          label={deductionTotal > 0 ? `Net Amount (after ${formatCurrency(deductionTotal)} deductions)` : 'Amount'}
          type="number"
          min="0"
          required
          value={amount}
          onChange={(e) => setAmount(e.target.value)}
        />

        <Input label="Month (optional)" value={month} onChange={(e) => setMonth(e.target.value)} placeholder="e.g. July 2026" />

        {accounts.length > 0 && (
          <Select label="Pay from account (optional)" value={accountId} onChange={(e) => setAccountId(e.target.value)}>
            <option value="">Don&apos;t record against an account</option>
            {accounts.map((a) => (
              <option key={a.id} value={a.id}>{a.name}</option>
            ))}
          </Select>
        )}

        <Textarea label="Notes (optional)" value={notes} onChange={(e) => setNotes(e.target.value)} rows={2} />

        {error && <p className="text-sm text-brand-red">{error}</p>}
      </form>
    </Modal>
  );
}
